// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40ESx7K0u2_XbWrkuBmkW6_oyXAKgiDU',
    appId: '1:507199562279:web:ae61bc338eabaaa9136402',
    messagingSenderId: '507199562279',
    projectId: 'barberapp-c208b',
    authDomain: 'barberapp-c208b.firebaseapp.com',
    storageBucket: 'barberapp-c208b.appspot.com',
    measurementId: 'G-DNX4DV1KL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOeUQHyA-iHi-SLHfN7jtczEJZHBKDp2Y',
    appId: '1:507199562279:android:fead6ed3a79b1887136402',
    messagingSenderId: '507199562279',
    projectId: 'barberapp-c208b',
    storageBucket: 'barberapp-c208b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNqk6jiCn7WLeOJT66Al8poVJeD0wqob4',
    appId: '1:507199562279:ios:e151dcc92db33aec136402',
    messagingSenderId: '507199562279',
    projectId: 'barberapp-c208b',
    storageBucket: 'barberapp-c208b.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNqk6jiCn7WLeOJT66Al8poVJeD0wqob4',
    appId: '1:507199562279:ios:e151dcc92db33aec136402',
    messagingSenderId: '507199562279',
    projectId: 'barberapp-c208b',
    storageBucket: 'barberapp-c208b.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB40ESx7K0u2_XbWrkuBmkW6_oyXAKgiDU',
    appId: '1:507199562279:web:4e8bbfec1ddf3602136402',
    messagingSenderId: '507199562279',
    projectId: 'barberapp-c208b',
    authDomain: 'barberapp-c208b.firebaseapp.com',
    storageBucket: 'barberapp-c208b.appspot.com',
    measurementId: 'G-FMX1QXYY3M',
  );
}
